version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3333:3333
    command: npm run start

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        USER_ID: ${USER_ID:-1337}
        GROUP_ID: ${GROUP_ID:-1337}
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4444:3333
    command: npm run test
