version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3333:3333
    command: npm run start

  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4444:3333
    command: npm run test