/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface UserAuthenticator {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLUserAuthenticatorElement extends Components.UserAuthenticator, HTMLStencilElement {}
  var HTMLUserAuthenticatorElement: {
    prototype: HTMLUserAuthenticatorElement;
    new (): HTMLUserAuthenticatorElement;
  };
  interface HTMLElementTagNameMap {
    'user-authenticator': HTMLUserAuthenticatorElement;
  }
}

declare namespace LocalJSX {
  interface UserAuthenticator extends JSXBase.HTMLAttributes<HTMLUserAuthenticatorElement> {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    'user-authenticator': UserAuthenticator;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


